---
title: "Cross-validations for FSI-article"
author: "Corresponding author"
date: "2024-02-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggnewscale) # Enables multiple colour- and fill-scales
library(latex2exp)
library(patchwork)
source("00_functions_and_global_definitions.R")

# The palette with grey:
cbp1 <- c("#999999", "#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

plot_title_size <- 7
axis_title_size <- 7
axis_ticks_size <- 7
legend_title_size <- 7
legend_text_size <- 7
```

## Scheme with the train data's list entrances (low range of DNA amounts)

Letter |      Train     | Test (low)
------ | -------------- | ----------
A      | 250, 125, 62.5 | 50, 31.25
B      | 50, 31.25      | 50, 31.25
C      | 125, 25        | 50, 31.25
D      | 50, 25         | 50, 31.25
E      | 31.25, 25      | 50, 31.25
F      | 50             | 50, 31.25
G      | 31.25          | 50, 31.25
H      | 25             | 50, 31.25
I      | 1000           | 50, 31.25
J      | 1000, 25       | 50, 31.25

# Testing on low dilutions (50pg and 31.25pg)
```{r}
m <- c("sqrt_NI", "sqrt", "log_NI", "log", "I_NI", "I")
datafile_name <- paste0("01_obj_crossval_", m, "_1K_9individuals_low.rds")

for (i in 1:6) {
dd_val_dils <- readRDS(file.path("..", "data", datafile_name[i]))
names(dd_val_dils) <- LETTERS[1:length(dd_val_dils)]

hsg_NN <- dd_val_dils |>
  sapply(function(d){
    sapply(d, function(r){
      r$HSG_NN
    })
  })

hsg_WC <- dd_val_dils |>
  sapply(function(d){
    sapply(d, function(r){
      r$HSG_WC
    })
  })


smlr_NN <- dd_val_dils |>
  sapply(function(d){
    sapply(d, function(r){
      length(r$p_NN)
    })
  })

smlr_WC <- dd_val_dils |>
  sapply(function(d){
    sapply(d, function(r){
      length(r$p_WC)
    })
  })

# SMLR's number of no-calls, when making same number of WCs as HSG
smlr_hsg_NN <- dd_val_dils |>
  sapply(function(d){
    sapply(d, function(r){
      hsg_wc <- r$HSG_WC
      if (length(r$p_WC) > hsg_wc) {
        p <- rev(r$p_WC)[hsg_wc+1]
        # NOTE: rev(r$p_WC) is listed from high to low, so it's right end (lower end)
        # has the lowest probabilities and is turned into NCs first.
        # Therefore, the entry hsg_wc+1 is the last entry we need to turn into an NC
        # before SMLR has a number of hsg_wc wrong calls. 
        n_NN <- sum(r$p_NN <= p) + sum(r$p_WC <= p)
      } else {
        n_NN <- 0
      }
    })
  })

# SMLR's number of WCs, when making same number of no-calls as HSG
smlr_hsg_WC <- dd_val_dils |>
  sapply(function(d){
    sapply(d, function(r){
      hsg_nc <- r$HSG_NN
      p_all <- c(r$p_WC, r$p_NN)
      if (length(p_all) > hsg_nc) {
        p_all <- p_all[order(p_all)]
        # NOTE: p_all is listed from low to high, so entry hsg_nc is the last
        # point we need to turn into an NC, before SMLR makes at least as many
        # no-calls has HSG. If any, we now want to find the WCs with p strictly
        # higher than this found point.
        p <- p_all[hsg_nc]
        n_WC <- sum(r$p_WC > p)
      } else {
        n_WC <- 0
      }
    })
  })


NN_HSG <- as.data.frame(hsg_NN)
NN_HSG <- lapply(NN_HSG, function(v){v[order(v)]}) |> bind_cols()
saveRDS(NN_HSG |> mutate(Model = m[i]), file.path("..", "data", paste0("02-obj-NN-HSG-", m[i], "-low.rds")))

WC_HSG <- as.data.frame(hsg_WC)
WC_HSG <- lapply(WC_HSG, function(v){v[order(v)]}) |> bind_cols()
saveRDS(WC_HSG |> mutate(Model = m[i]), file.path("..", "data", paste0("02-obj-WC-HSG-", m[i], "-low.rds")))

NN_SMLR_HSG <- as.data.frame(smlr_hsg_NN)
NN_SMLR_HSG <- lapply(NN_SMLR_HSG, function(v){v[order(v)]}) |> bind_cols()
saveRDS(NN_SMLR_HSG |> mutate(Model = m[i]), file.path("..", "data", paste0("02-obj-NN-SMLR-HSG-", m[i], "-low.rds")))

WC_SMLR_HSG <- as.data.frame(smlr_hsg_WC)
WC_SMLR_HSG <- lapply(WC_SMLR_HSG, function(v){v[order(v)]}) |> bind_cols()
saveRDS(WC_SMLR_HSG |> mutate(Model = m[i]), file.path("..", "data", paste0("02-obj-WC-SMLR-HSG-", m[i], "-low.rds")))


NN_reduction_hsg <- as.data.frame((hsg_NN - smlr_hsg_NN)/hsg_NN)
NN_reduction_hsg <- lapply(NN_reduction_hsg, function(v){v[order(v)]}) |> bind_cols()
saveRDS(NN_reduction_hsg |> mutate(Model = m[i]), file.path("..", "data", paste0("02-obj-NNred-HSG-", m[i], "-low.rds")))

WC_reduction_hsg <- (hsg_WC - smlr_hsg_WC)/hsg_WC
WC_reduction_hsg[hsg_WC == 0] <- -Inf
WC_reduction_hsg[hsg_WC - smlr_hsg_WC == 0] <- 0
WC_reduction_hsg <- as.data.frame(WC_reduction_hsg)
WC_reduction_hsg <- lapply(WC_reduction_hsg, function(v){v[order(v)]}) |> bind_cols()
saveRDS(WC_reduction_hsg |> mutate(Model = m[i]), file.path("..", "data", paste0("02-obj-WCred-HSG-", m[i], "-low.rds")))
}
```


# Comparison of all cross-validations
```{r}
files_in_data <- list.files(file.path("..", "data"))
files_in_data <- files_in_data[str_ends(files_in_data, "-low.rds")]

cv_NN_files <- files_in_data[str_starts(files_in_data, "02-obj-NN")]
cv_NNred_files <- cv_NN_files[str_starts(cv_NN_files, "02-obj-NNred")]
cv_NN_files <- cv_NN_files[str_starts(cv_NN_files, "02-obj-NNred", negate = T)]

cv_WC_files <- files_in_data[str_starts(files_in_data, "02-obj-WC")]
cv_WCred_files <- cv_WC_files[str_starts(cv_WC_files, "02-obj-WCred")]
cv_WC_files <- cv_WC_files[str_starts(cv_WC_files, "02-obj-WCred", negate = T)]
```

```{r}
NNs_low <- lapply(cv_NN_files, function(x) {
  readRDS(file.path("..", "data", x)) |> 
    rownames_to_column(var = "Percentile") |> 
    mutate(Percentile = as.integer(Percentile)/10,
           Method = sub("02-obj-NN-(.*)-.*-.*\\.rds", "\\1", x)) |> 
    mutate(Model = if_else(Method %in% c("HSG", "EQC"), Method, Model))
}) |> bind_rows() |> 
  group_by(Percentile, Model, Method) |>
  summarise("A" = median(A),
            "B" = median(B),
            "C" = median(C),
            "D" = median(D),
            "E" = median(E),
            "F" = median(F),
            "G" = median(G),
            "H" = median(H),
            "I" = median(I),
            "J" = median(J),
            .groups = 'drop')

NN_reductions_low <- lapply(cv_NNred_files, function(x) {
  readRDS(file.path("..", "data", x)) |> 
    rownames_to_column(var = "Percentile") |> 
    mutate(Percentile = as.integer(Percentile)/10,
           Method = sub("02-obj-NNred-(.*)-.*-.*\\.rds", "\\1", x))
}) |> bind_rows()
NN_reductions_low[,2:11] <- NN_reductions_low[,2:11]*100
```

```{r}
WCs_low <- lapply(cv_WC_files, function(x) {
  readRDS(file.path("..", "data", x)) |> 
    rownames_to_column(var = "Percentile") |> 
    mutate(Percentile = as.integer(Percentile)/10,
           Method = sub("02-obj-WC-(.*)-.*-.*\\.rds", "\\1", x)) |> 
    mutate(Model = if_else(Method %in% c("HSG", "EQC"), Method, Model))
}) |> bind_rows() |> 
  group_by(Percentile, Model, Method) |>
  summarise("A" = median(A),
            "B" = median(B),
            "C" = median(C),
            "D" = median(D),
            "E" = median(E),
            "F" = median(F),
            "G" = median(G),
            "H" = median(H),
            "I" = median(I),
            "J" = median(J),
            .groups = 'drop')

WC_reductions_low <- lapply(cv_WCred_files, function(x) {
  readRDS(file.path("..", "data", x)) |> 
    rownames_to_column(var = "Percentile") |> 
    mutate(Percentile = as.integer(Percentile)/10,
           Method = sub("02-obj-WCred-(.*)-.*-.*\\.rds", "\\1", x))
}) |> bind_rows()
WC_reductions_low[,2:11] <- WC_reductions_low[,2:11]*100
```

# Cross validations (reduction in no-calls)
### SMLR's performance when making the same number of WC as HSG
```{r}
(p_hsg1_NC_low <- NN_reductions_low |> filter(Method == "HSG") |> 
  ggplot(aes(x = Percentile, y = D, colour = Model)) +
  geom_hline(yintercept = 0, lty = "dashed") + 
  geom_line(show.legend = F) +
  coord_cartesian(ylim = c(-50, 100)) +
  ylab("Reduction in no-calls [%]\n(when aligned to HSG's #WCs)") + 
  ggtitle("Fit: 25pg, 50pg\nTest: 31.25pg, 50pg") +
  theme_bw() +
  theme(axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        axis.title.x=element_text(size = axis_title_size),
        axis.text.y=element_text(size = axis_ticks_size),
        axis.title.y=element_text(size = axis_title_size),
        plot.title = element_text(size = plot_title_size)))

(p_hsg2_NC_low <- NN_reductions_low |> filter(Method == "HSG") |> 
  ggplot(aes(x = Percentile, y = B, colour = Model)) +
  geom_hline(yintercept = 0, lty = "dashed") + 
  geom_line(show.legend = F) + 
  coord_cartesian(ylim = c(-50, 100)) +
  ggtitle("31.25pg, 50pg\n") +
  theme_bw() +
  theme(axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        axis.title.x=element_text(size = axis_title_size),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        plot.title = element_text(size = plot_title_size)))

(p_hsg8_NC_low <- NN_reductions_low |> filter(Method == "HSG") |> 
  ggplot(aes(x = Percentile, y = J, colour = Model)) +
  geom_hline(yintercept = 0, lty = "dashed") + 
  geom_line(show.legend = F) + 
  coord_cartesian(ylim = c(-50, 100)) + 
  ggtitle("25pg, 1000pg\n") +
  theme_bw() +
  theme(axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        axis.title.x=element_text(size = axis_title_size),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        plot.title = element_text(size = plot_title_size)))

```

### SMLR's performance when making the same number of NC as HSG
```{r}
(p_hsg1_WC_low <- WC_reductions_low |> filter(Method == "HSG") |> 
  ggplot(aes(x = Percentile, y = D, colour = Model)) +
  geom_hline(yintercept = 0, lty = "dashed") + 
  geom_line(show.legend = F) +
  coord_cartesian(ylim = c(-50, 100)) +
  ylab("Reduction in wrong calls [%]\n(when aligned to HSG's #NCs)") +
  theme_bw() +
  theme(axis.text.x=element_text(size = axis_ticks_size),
        axis.title.x=element_text(size = axis_title_size),
        axis.text.y=element_text(size = axis_ticks_size),
        axis.title.y=element_text(size = axis_title_size),
        plot.title = element_text(size = plot_title_size)))

(p_hsg2_WC_low <- WC_reductions_low |> filter(Method == "HSG") |> 
  ggplot(aes(x = Percentile, y = B, colour = Model)) +
  geom_hline(yintercept = 0, lty = "dashed") + 
  geom_line(show.legend = F) + 
  coord_cartesian(ylim = c(-50, 100)) +
  theme_bw() +
  theme(axis.text.x=element_text(size = axis_ticks_size),
        axis.title.x=element_text(size = axis_title_size),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        plot.title = element_text(size = plot_title_size)))

(p_hsg8_WC_low <- WC_reductions_low |> filter(Method == "HSG") |> 
  ggplot(aes(x = Percentile, y = J, colour = Model)) +
  geom_hline(yintercept = 0, lty = "dashed") + 
  geom_line(show.legend = F) + 
  coord_cartesian(ylim = c(-50, 100)) + 
  theme_bw() +
  theme(axis.text.x=element_text(size = axis_ticks_size),
        axis.title.x=element_text(size = axis_title_size),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        plot.title = element_text(size = plot_title_size)))

```



# Testing on high dilutions (250pg, 125pg, 62.5pg)

## Scheme with the train data's list entrances (high range of DNA amounts)

Letter |      Train     | Test (low)
------ | -------------- | --------------
A      | 250, 125, 62.5 | 250, 125, 62.5
B      | 50, 31.25      | 250, 125, 62.5
C      | 125, 25        | 250, 125, 62.5
D      | 50, 25         | 250, 125, 62.5
E      | 31.25, 25      | 250, 125, 62.5
F      | 50             | 250, 125, 62.5
G      | 31.25          | 250, 125, 62.5
H      | 25             | 250, 125, 62.5
I      | 1000           | 250, 125, 62.5
J      | 1000, 25       | 250, 125, 62.5

```{r}
datafile_name <- paste0("01_obj_crossval_", m, "_1K_9individuals_high.rds")

for (i in 1:6) {
dd_val_dils <- readRDS(file.path("..", "data", datafile_name[i]))
names(dd_val_dils) <- LETTERS[1:length(dd_val_dils)]

hsg_NN <- dd_val_dils |>
  sapply(function(d){
    sapply(d, function(r){
      r$HSG_NN
    })
  })

hsg_WC <- dd_val_dils |>
  sapply(function(d){
    sapply(d, function(r){
      r$HSG_WC
    })
  })


smlr_NN <- dd_val_dils |>
  sapply(function(d){
    sapply(d, function(r){
      length(r$p_NN)
    })
  })

smlr_WC <- dd_val_dils |>
  sapply(function(d){
    sapply(d, function(r){
      length(r$p_WC)
    })
  })

# SMLR's number of no-calls, when making same number of WCs as HSG
smlr_hsg_NN <- dd_val_dils |>
  sapply(function(d){
    sapply(d, function(r){
      hsg_wc <- r$HSG_WC
      if (length(r$p_WC) > hsg_wc) {
        p <- rev(r$p_WC)[hsg_wc+1]
        # NOTE: rev(r$p_WC) is listed from high to low, so it's right end (lower end)
        # has the lowest probabilities and is turned into NCs first.
        # Therefore, the entry hsg_wc+1 is the last entry we need to turn into an NC
        # before SMLR has a number of hsg_wc wrong calls. 
        n_NN <- sum(r$p_NN <= p) + sum(r$p_WC <= p)
      } else {
        n_NN <- 0
      }
    })
  })

# SMLR's number of WCs, when making same number of no-calls as HSG
smlr_hsg_WC <- dd_val_dils |>
  sapply(function(d){
    sapply(d, function(r){
      hsg_nc <- r$HSG_NN
      p_all <- c(r$p_WC, r$p_NN)
      if (length(p_all) > hsg_nc) {
        p_all <- p_all[order(p_all)]
        # NOTE: p_all is listed from low to high, so entry hsg_nc is the last
        # point we need to turn into an NC, before SMLR makes at least as many
        # no-calls has HSG. If any, we now want to find the WCs with p strictly
        # higher than this found point.
        p <- p_all[hsg_nc]
        n_WC <- sum(r$p_WC > p)
      } else {
        n_WC <- 0
      }
    })
  })


NN_HSG <- as.data.frame(hsg_NN)
NN_HSG <- lapply(NN_HSG, function(v){v[order(v)]}) |> bind_cols()
saveRDS(NN_HSG |> mutate(Model = m[i]), file.path("..", "data", paste0("02-obj-NN-HSG-", m[i], "-high.rds")))

WC_HSG <- as.data.frame(hsg_WC)
WC_HSG <- lapply(WC_HSG, function(v){v[order(v)]}) |> bind_cols()
saveRDS(WC_HSG |> mutate(Model = m[i]), file.path("..", "data", paste0("02-obj-WC-HSG-", m[i], "-high.rds")))

NN_SMLR_HSG <- as.data.frame(smlr_hsg_NN)
NN_SMLR_HSG <- lapply(NN_SMLR_HSG, function(v){v[order(v)]}) |> bind_cols()
saveRDS(NN_SMLR_HSG |> mutate(Model = m[i]), file.path("..", "data", paste0("02-obj-NN-SMLR-HSG-", m[i], "-high.rds")))

WC_SMLR_HSG <- as.data.frame(smlr_hsg_WC)
WC_SMLR_HSG <- lapply(WC_SMLR_HSG, function(v){v[order(v)]}) |> bind_cols()
saveRDS(WC_SMLR_HSG |> mutate(Model = m[i]), file.path("..", "data", paste0("02-obj-WC-SMLR-HSG-", m[i], "-high.rds")))


# NN_SMLR <- as.data.frame(smlr_NN)
# NN_SMLR <- lapply(NN_SMLR, function(v){v[order(v)]}) |> bind_cols()
# saveRDS(NN_SMLR |> mutate(Model = m[i]), file.path("..", "data", paste0("02-obj-NN-SMLR-0WC-", m[i], "-high.rds")))

# WC_SMLR <- as.data.frame(smlr_WC)
# WC_SMLR <- lapply(WC_SMLR, function(v){v[order(v)]}) |> bind_cols()
# saveRDS(WC_SMLR |> mutate(Model = m[i]), file.path("..", "data", paste0("02-obj-WC-SMLR-0WC-", m[i], "-high.rds")))

NN_reduction_hsg <- as.data.frame((hsg_NN - smlr_hsg_NN)/hsg_NN)
NN_reduction_hsg <- lapply(NN_reduction_hsg, function(v){v[order(v)]}) |> bind_cols()
saveRDS(NN_reduction_hsg |> mutate(Model = m[i]), file.path("..", "data", paste0("02-obj-NNred-HSG-", m[i], "-high.rds")))

WC_reduction_hsg <- (hsg_WC - smlr_hsg_WC)/hsg_WC
WC_reduction_hsg[hsg_WC == 0] <- -Inf
WC_reduction_hsg[hsg_WC - smlr_hsg_WC == 0] <- 0
WC_reduction_hsg <- as.data.frame(WC_reduction_hsg)
WC_reduction_hsg <- lapply(WC_reduction_hsg, function(v){v[order(v)]}) |> bind_cols()
saveRDS(WC_reduction_hsg |> mutate(Model = m[i]), file.path("..", "data", paste0("02-obj-WCred-HSG-", m[i], "-high.rds")))
}
```


# Comparison of all crosvalidations
```{r}
files_in_data <- list.files(file.path("..", "data"))
files_in_data <- files_in_data[str_ends(files_in_data, "-high.rds")]

cv_NN_files <- files_in_data[str_starts(files_in_data, "02-obj-NN")]
cv_NNred_files <- cv_NN_files[str_starts(cv_NN_files, "02-obj-NNred")]
cv_NN_files <- cv_NN_files[str_starts(cv_NN_files, "02-obj-NNred", negate = T)]

cv_WC_files <- files_in_data[str_starts(files_in_data, "02-obj-WC")]
cv_WCred_files <- cv_WC_files[str_starts(cv_WC_files, "02-obj-WCred")]
cv_WC_files <- cv_WC_files[str_starts(cv_WC_files, "02-obj-WCred", negate = T)]
```

```{r}
NNs_high <- lapply(cv_NN_files, function(x) {
  readRDS(file.path("..", "data", x)) |> 
    rownames_to_column(var = "Percentile") |> 
    mutate(Percentile = as.integer(Percentile)/10,
           Method = sub("02-obj-NN-(.*)-.*-.*\\.rds", "\\1", x)) |> 
    mutate(Model = if_else(Method %in% c("HSG", "EQC"), Method, Model))
}) |> bind_rows() |> 
  group_by(Percentile, Model, Method) |>
  summarise("A" = median(A),
            "B" = median(B),
            "C" = median(C),
            "D" = median(D),
            "E" = median(E),
            "F" = median(F),
            "G" = median(G),
            "H" = median(H),
            "I" = median(I),
            "J" = median(J),
            .groups = 'drop')

NN_reductions_high <- lapply(cv_NNred_files, function(x) {
  readRDS(file.path("..", "data", x)) |> 
    rownames_to_column(var = "Percentile") |> 
    mutate(Percentile = as.integer(Percentile)/10,
           Method = sub("02-obj-NNred-(.*)-.*-.*\\.rds", "\\1", x))
}) |> bind_rows()
NN_reductions_high[,2:11] <- NN_reductions_high[,2:11]*100
```

```{r}
WCs_high <- lapply(cv_WC_files, function(x) {
  readRDS(file.path("..", "data", x)) |> 
    rownames_to_column(var = "Percentile") |> 
    mutate(Percentile = as.integer(Percentile)/10,
           Method = sub("02-obj-WC-(.*)-.*-.*\\.rds", "\\1", x)) |> 
    mutate(Model = if_else(Method %in% c("HSG", "EQC"), Method, Model))
}) |> bind_rows() |> 
  group_by(Percentile, Model, Method) |>
  summarise("A" = median(A),
            "B" = median(B),
            "C" = median(C),
            "D" = median(D),
            "E" = median(E),
            "F" = median(F),
            "G" = median(G),
            "H" = median(H),
            "I" = median(I),
            "J" = median(J),
            .groups = 'drop')

WC_reductions_high <- lapply(cv_WCred_files, function(x) {
  readRDS(file.path("..", "data", x)) |> 
    rownames_to_column(var = "Percentile") |> 
    mutate(Percentile = as.integer(Percentile)/10,
           Method = sub("02-obj-WCred-(.*)-.*-.*\\.rds", "\\1", x))
}) |> bind_rows()
WC_reductions_high[,2:11] <- WC_reductions_high[,2:11]*100
```


# Cross validations (reduction in no-calls)
### SMLR's performance when making the same number of WC as HSG
```{r}
(p_hsg1_NC_high <- NN_reductions_high |> filter(Method == "HSG") |> 
  ggplot(aes(x = Percentile, y = D, colour = Model)) +
  geom_hline(yintercept = 0, lty = "dashed") + 
  geom_line(show.legend = F) +
  coord_cartesian(ylim = c(-50, 100)) +
  ggtitle("Fit: 25pg, 50pg\nTest: 62.5–250pg") +
  theme_bw() +
  theme(axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        axis.title.x=element_text(size = axis_title_size),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        plot.title = element_text(size = plot_title_size)))

(p_hsg2_NC_high <- NN_reductions_high |> filter(Method == "HSG") |> 
  ggplot(aes(x = Percentile, y = B, colour = Model)) +
  geom_hline(yintercept = 0, lty = "dashed") + 
  geom_line(show.legend = F) + 
  coord_cartesian(ylim = c(-50, 100)) +
  ggtitle("31.25pg, 50pg\n") +
  theme_bw() +
  theme(axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        axis.title.x=element_text(size = axis_title_size),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        plot.title = element_text(size = plot_title_size)))

(p_hsg8_NC_high <- NN_reductions_high |> filter(Method == "HSG") |> 
  ggplot(aes(x = Percentile, y = J, colour = Model)) +
  geom_hline(yintercept = 0, lty = "dashed") + 
  geom_line(show.legend = F) + 
  coord_cartesian(ylim = c(-50, 100)) + 
  ggtitle("25pg, 1000pg\n") +
  theme_bw() +
  theme(axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        axis.title.x=element_text(size = axis_title_size),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        plot.title = element_text(size = plot_title_size)))
```

### SMLR's performance when making the same number of NC as HSG
```{r}
(p_hsg1_WC_high <- WC_reductions_high |> filter(Method == "HSG") |> 
  ggplot(aes(x = Percentile, y = D, colour = Model)) +
  geom_hline(yintercept = 0, lty = "dashed") + 
  geom_line(show.legend = F) +
  coord_cartesian(ylim = c(-50, 100)) +
  theme_bw() +
  theme(axis.text.x=element_text(size = axis_ticks_size),
        axis.title.x=element_text(size = axis_title_size),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        plot.title = element_text(size = plot_title_size)))

(p_hsg2_WC_high <- WC_reductions_high |> filter(Method == "HSG") |> 
  ggplot(aes(x = Percentile, y = B, colour = Model)) +
  geom_hline(yintercept = 0, lty = "dashed") + 
  geom_line(show.legend = F) + 
  coord_cartesian(ylim = c(-50, 100)) +
  theme_bw() +
  theme(axis.text.x=element_text(size = axis_ticks_size),
        axis.title.x=element_text(size = axis_title_size),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        plot.title = element_text(size = plot_title_size)))

(p_hsg8_WC_high <- WC_reductions_high |> filter(Method == "HSG") |> 
  ggplot(aes(x = Percentile, y = J, colour = Model)) +
  geom_hline(yintercept = 0, lty = "dashed") + 
  geom_line() + 
  coord_cartesian(ylim = c(-50, 100)) + 
  theme_bw() +
  theme(axis.text.x=element_text(size = axis_ticks_size),
        axis.title.x=element_text(size = axis_title_size),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        plot.title = element_text(size = plot_title_size),
        legend.title = element_text(size = legend_title_size),
        legend.text = element_text(size = legend_text_size)))
```

```{r}
p <- p_hsg1_NC_low + p_hsg2_NC_low + p_hsg8_NC_low + p_hsg1_NC_high + p_hsg2_NC_high + p_hsg8_NC_high +
      p_hsg1_WC_low + p_hsg2_WC_low + p_hsg8_WC_low + p_hsg1_WC_high + p_hsg2_WC_high + p_hsg8_WC_high +
      plot_layout(ncol = 6, nrow = 2, byrow = T, guides = "collect", axis_titles = "collect_x")  &
   scale_colour_manual(values=cbp1,
                      labels = unname(c(TeX("$I$"),
                                        TeX("$I, \\beta_0 = 0$"),
                                        TeX("$log$"),
                                        TeX("$log, \\beta_0 = 0$"),
                                        TeX("$sqrt$"),
                                        TeX("$sqrt, \\beta_0 = 0$"))))
for (i in seq_along(p)) {
  if (i%%6 == 1) { # leftmost plots
    p[[i]]$theme$plot.margin[4] <- 0*p[[i]]$theme$plot.margin[4]
  } else if (i%%6 == 0) { # rightmost plots
    p[[i]]$theme$plot.margin[2] <- 0*p[[i]]$theme$plot.margin[2]
  }
  if (i <= 6) { # top row of plots
    p[[i]]$theme$plot.margin[1] <- 0*p[[i]]$theme$plot.margin[1]
  } else if (i > 6) { # bottom row of plots
    p[[i]]$theme$plot.margin[3] <- 0*p[[i]]$theme$plot.margin[3]
  }
  # All plots should have their legend's right margin set to zero
  p[[i]]$theme$legend.margin[2] <- 0*p[[i]]$theme$legend.margin[2]
}
# The overall margins added by patchwork is set to zero:
(p <- p + plot_annotation(theme = theme(plot.margin = margin(t=0, r=0, b=0, l=0, unit = 'pt'))))

ggsave(filename = file.path("..", "article-FSIGEN", "FIG_S2-two-column.bmp"),
       plot = p, device = "bmp", width = 7480, height = 3425, units = "px", dpi = 1000)
```

# Summary statistics for article
```{r}
# B is fitting on 50 & 31.25
# J is fitting on 1000 & 25
# D is fitting on 50 & 25
# (sqrt_red_low <- (NN_reductions_low |> filter(Model == "sqrt", Percentile == 50))[,c("Percentile", "Model", "Method", "B", "J", "D")])
# (sqrt_red_high <- (NN_reductions_high |> filter(Model == "sqrt", Percentile == 50))[,c("Percentile", "Model", "Method", "B", "J", "D")])

sqrt_NCred_low <- (NN_reductions_low |> filter(Model == "sqrt", Percentile %in% c(0.1, 50, 100)))[,c("Percentile", "Model", "D")]
sqrt_WCred_low <- (WC_reductions_low |> filter(Model == "sqrt", Percentile %in% c(0.1, 50, 100)))[,c("Percentile", "Model", "D")]
sqrt_NCred_high <- (NN_reductions_high |> filter(Model == "sqrt", Percentile %in% c(0.1, 100)))[,c("Percentile", "Model", "D")]
sqrt_WCred_high <- (WC_reductions_high |> filter(Model == "sqrt", Percentile %in% c(0.1, 100)))[,c("Percentile", "Model", "D")]

data.frame("Test dil" = c(rep("Low", 6), rep("High", 4)),
           "Type" = c(rep(c("NC", "WC"), each = 3), rep(c("NC", "WC"), each = 2))) |> 
  bind_cols(sqrt_NCred_low |> bind_rows(sqrt_WCred_low) |> bind_rows(sqrt_NCred_high) |> bind_rows(sqrt_WCred_high)) |> 
  mutate("Relative reduction" = round(D, digits = 1)) |> select(-D)
```

