---
title: "Scatterplots"
author: "Corresponding author"
date: "2023-12-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggnewscale) # Enables multiple colour- and fill-scales
library(latex2exp)
library(patchwork)
source("00_functions_and_global_definitions.R")

plot_title_size <- 7
axis_title_size <- 7
axis_ticks_size <- 7
legend_title_size <- 7
legend_text_size <- 7
```

```{r Reading data}
dd_GT <- readRDS(file.path("..", "data", "00_dd_GT.rds"))
dd_GT_2nd <- readRDS(file.path("..", "data", "00_dd_GT_2nd.rds"))
true_profiles_2nd <- readRDS(file.path("..", "data", "00_true_profiles_2nd.rds"))

dd_GT_both <- dd_GT_2nd |> bind_rows(dd_GT[names(dd_GT_2nd)])

```


# Scatterplot of data for each relevant dilution
## with the HID SNP Genotyper's suggested genotype predictions
```{r warning=FALSE}
(p1 <- plot_machine(filter(dd_GT_both, Dilution == "250"), f = sqrt, legend = FALSE, title = "250pg", x_lim = c(0,60), y_lim = c(0,60)))
(p2 <- plot_machine(filter(dd_GT_both, Dilution == "125"), f = sqrt, legend = FALSE, title = "125pg", x_lim = c(0,60), y_lim = c(0,60)))
(p3 <- plot_machine(filter(dd_GT_both, Dilution == "62.5"), f = sqrt, legend = FALSE, title = "62.5pg", x_lim = c(0,60), y_lim = c(0,60)))
(p4 <- plot_machine(filter(dd_GT_both, Dilution == "50"), f = sqrt, legend = FALSE, title = "50pg", x_lim = c(0,60), y_lim = c(0,60)))
(p5 <- plot_machine(filter(dd_GT_both, Dilution == "31.25"), f = sqrt, legend = FALSE, title = "31.25pg", x_lim = c(0,60), y_lim = c(0,60)))
(p6 <- plot_machine(filter(dd_GT_both, Dilution == "25"), f = sqrt, legend = FALSE, title = "25pg", x_lim = c(0,60), y_lim = c(0,60)))
(p7 <- plot_machine(filter(dd_GT_both, Dilution == "12.5"), f = sqrt, legend = FALSE, title = "12.5pg", x_lim = c(0,60), y_lim = c(0,60)))
(p8 <- plot_machine(filter(dd_GT_both, Dilution == "6.25"), f = sqrt, legend = T, title = "6.25pg", x_lim = c(0,60), y_lim = c(0,60)) +
    theme(legend.title = element_text(size = legend_title_size),
          legend.text = element_text(size = legend_text_size)))
```

```{r warning=FALSE}
p <- p1 + p2 + p3 + p4 +
      p5 + p6 + p7 + p8 +
      plot_layout(ncol = 4, nrow = 2, byrow = T, guides = "collect", axes = "collect", axis_titles = "collect") &
      xlab(TeX("$\\sqrt{s_1}$")) & ylab(TeX("$\\sqrt{s_2}$")) &
      theme(plot.title = element_text(size = plot_title_size),
            axis.title = element_text(size = axis_title_size),
            axis.text = element_text(size = axis_ticks_size))

for (i in seq_along(p)) {
  if (i%%4 == 1) { # leftmost plots
    p[[i]]$theme$plot.margin[4] <- 0*p[[i]]$theme$plot.margin[4]
  } else if (i%%4 == 0) { # rightmost plots
    p[[i]]$theme$plot.margin[2] <- 0*p[[i]]$theme$plot.margin[2]
  }
  if (i <= 4) { # top row of plots
    p[[i]]$theme$plot.margin[1] <- 0*p[[i]]$theme$plot.margin[1]
  } else if (i > 4) { # bottom row of plots
    p[[i]]$theme$plot.margin[3] <- 0*p[[i]]$theme$plot.margin[3]
  }
  # All plots should have their legend's right margin set to zero
  p[[i]]$theme$legend.margin[2] <- 0*p[[i]]$theme$legend.margin[2]
}
# The overall margins added by patchwork is set to zero:
(p <- p + plot_annotation(theme = theme(plot.margin = margin(t=0, r=0, b=0, l=0, unit = 'pt'))))

ggsave(filename = file.path("..", "article-FSIGEN", "FIG_2-two-column.bmp"),
       plot = p, device = "bmp", width = 7480, height = 3740, units = "px", dpi = 1000)
```

```{r warning=FALSE}
(ph <- plot_machine(filter(dd_GT_both, Dilution == "31.25"), f = sqrt, legend = FALSE, title = "HSG") + ylab(TeX("$\\sqrt{s_2}$")) + coord_fixed(xlim = c(0,34), ylim = c(0,34)) +
   theme(plot.title = element_text(size = plot_title_size),
         axis.title.y = element_text(size = axis_title_size),
         axis.text = element_text(size = axis_ticks_size),
         axis.title.x = element_blank()))

(pr <- plot_EQC(filter(dd_GT_both, Dilution == "31.25"), f = sqrt, title = "EQC") + 
    xlab(TeX("$\\sqrt{s_1}$")) + ylab(TeX("$\\sqrt{s_2}$")) + coord_fixed(xlim = c(0,34), ylim = c(0,34)) +
    theme(plot.title = element_text(size = plot_title_size),
          axis.title.x = element_text(size = axis_title_size),
          axis.text.x = element_text(size = axis_ticks_size),
          axis.ticks.y=element_blank(),
          axis.text.y=element_blank(),
          axis.title.y=element_blank(),
          legend.title = element_text(size = legend_title_size),
          legend.text = element_text(size = legend_text_size)))
 
m_fit <- fit_symmetry_model2(df = filter(dd_GT_both, Dilution == "31.25"), f = sqrt, intercept = T, b_int = c(0, 1,-2))
(pm <- plot_model(df = filter(dd_GT_both, Dilution == "31.25"), intercept_model = m_fit, predictions = "No intercept", q = 0.9937, q_digits = 4) + 
    ggtitle("SMLR") + coord_fixed(xlim = c(0,34), ylim = c(0,34)) +
    theme(plot.title = element_text(size = plot_title_size),
          axis.text.x = element_text(size = axis_ticks_size),
          axis.title.x=element_blank(),
          axis.ticks.y=element_blank(),
          axis.text.y=element_blank(),
          axis.title.y=element_blank(),
          legend.title = element_text(size = legend_title_size),
          legend.text = element_text(size = legend_text_size)))
```

```{r warning=FALSE}
p <- ph + pr + pm + 
   plot_layout(ncol = 3, nrow = 1, byrow = T, guides = "collect") &
   theme(legend.spacing.y = unit(0, 'mm'),
         legend.margin = margin(t=4.5, r=0, b=4.5, l=5.5, unit = 'pt'),
         legend.key.spacing = unit(1, 'mm'),
         legend.key.height = unit(4, 'mm'),
         plot.margin = margin(t=0, r=5.5, b=0, l=5.5, unit = 'pt'))

p[[1]]$theme$plot.margin[4] <- 0*p[[1]]$theme$plot.margin[4]
p[[3]]$theme$plot.margin[2] <- 0*p[[3]]$theme$plot.margin[2]
(p <- p + plot_annotation(theme = theme(plot.margin = margin(t=0, r=0, b=0, l=0, unit = 'pt'))))

ggsave(filename = file.path("..", "article-FSIGEN", "FIG_1-two-column.bmp"),
       plot = p, device = "bmp", width = 7480, height = 2330, units = "px", dpi = 1000)
```

## Plotting both intercept and no intercept model
```{r}
# m_fit <- fit_symmetry_model2(df = filter(dd_GT_both, Dilution %in% c("31.25", "50")), f = sqrt, intercept = T, b_int = c(0, 1,-2))
# m_fit_NI <- fit_symmetry_model2(df = filter(dd_GT_both, Dilution %in% c("31.25", "50")), f = sqrt, intercept = F, b_int = c(1,-2))
# (pm <- plot_model(df = filter(dd_GT_both, Dilution %in% c("31.25", "50")), intercept_model = m_fit, NI_model = m_fit_NI, predictions = "No intercept", q = 0, q_digits = 4) + 
#     scale_linetype_manual(labels = unname(TeX(c("$\\beta_0\\neq 0$", "$\\beta_0=0$"))),
#                           values = c("dotted", "solid")) +
#     scale_shape_manual(values = 4) +
#     ggtitle("SMLR") + coord_fixed(xlim = c(0,34), ylim = c(0,34)) +
#   theme(axis.title.x=element_blank(),
#         axis.ticks.y=element_blank(),
#         axis.text.y=element_blank(),
#         axis.title.y=element_blank()))
# 
# ggsave(filename = file.path("..", "article-FSIGEN", "modelplot_both.bmp"), plot = pm,
#        device = "bmp", width = 15, height = 12, units = "cm")
```